### ISSUE TITLE
Add any Algorithm in any language, dont forget to read README file

### ISSUE THREAD

**Issue by khanaaziz1** [khanaaziz1/Hacktoberfest_2019#1]

**Comment by ssoham** [comment]
I added a few algorithms to the repo.

**Comment by HesamGm** [comment]
Hi @khanaaziz1, I would like to add a few sort algorithms

**Comment by khanaaziz1** [comment]
@HesamGm sure but make sure they are not already present and dont forget to read README

**Comment by MalkaSaba** [comment]
I added the bubble sort algorithm in java.

**Comment by RockLee444** [comment]
I added the Insertion sort algorithm in Java!
